// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

// Let us list the factors of the first seven triangle numbers:

// 1: 1
// 3: 1,3
// 6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.

// What is the value of the first triangle number to have over five hundred divisors;

function checkNumDivisors(){
    for (let i = 5000; i < 20000; i++){
        let nThTriangleNum = (i * (i + 1)) / 2;
        let divisors = [1];
        for (let i = 2; i <= Math.sqrt(nThTriangleNum); i++){
            if (divisors.includes(i)){
                
            }
            else {
                if (nThTriangleNum % i == 0){
                    if (i * i != nThTriangleNum){
                        divisors.push(i);
                        divisors.push(nThTriangleNum / i);
                    }
                    else{
                        divisors.push(i);
                    }
                }
            }
        }
        if (divisors.length > 500){
            console.log(nThTriangleNum, ", ", divisors.length, i);
            break;
        }
        
    }
}
checkNumDivisors();